name: 'Setup'
description: 'Install Rust Toolchain Components, just, and cross for building on multiple targets.'

runs:
  using: "composite"
  steps:
    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Install just
      uses: extractions/setup-just@v3

    - name: Install cross
      uses: taiki-e/install-action@v2
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      with:
        tool: cross

    - name: Install Wix Toolset 🛠
      if: ${{ startsWith(matrix.os, 'windows') }}
      shell: pwsh
      run: dotnet tool install --global wix

    - name: Install cargo-edit
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-edit

    - name: Install patch-crate
      uses: baptiste0928/cargo-install@v3
      with:
        crate: patch-crate

